import {
  createContext,
  useContext,
  useState,
  useEffect,
  ReactNode,
} from "react";

type Language = "en" | "mr";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(
  undefined
);

// Translation data
const translations = {
  en: {
    // Header
    "header.title": "Shree Kshetra Khandeshar Devasthan Kusalamb",
    "header.titleMarathi": "श्री क्षेत्र खंडेश्वर देवस्थान कुसळंब",
    "header.subtitle": "Temple Management System",
    "header.subtitleMarathi": "मंदिर व्यवस्थापन प्रणाली",
    "nav.dashboard": "Dashboard",
    "nav.donations": "Donations",
    "nav.expenses": "Expenses",
    "nav.reports": "Reports",
    "nav.users": "Users",
    "nav.rentManagement": "Rent Management",
    "user.settings": "Settings",
    "user.userManagement": "User Management",
    "user.logout": "Logout",
    "user.signedInAs": "Signed in as",

    // Login
    "login.welcome": "Welcome",
    "login.username": "Username",
    "login.password": "Password",
    "login.signIn": "Sign In",
    "login.signingIn": "Signing in...",
    "login.enterUsername": "Enter Your Username",
    "login.enterPassword": "Enter Your Password",
    "login.demoCredentials": "Demo Credentials:",
    "login.invalidCredentials":
      "Invalid username or password, or account is inactive",

    // Authentication
    "auth.loading": "Loading...",

    // Dashboard
    "dashboard.title": "Dashboard",
    "dashboard.totalDonations": "Total Donations",
    "dashboard.totalExpenses": "Total Expenses",
    "dashboard.netBalance": "Net Balance",
    "dashboard.recentTransactions": "Recent Transactions",
    "dashboard.viewAll": "View All",
    "dashboard.totalRentIncome": "Total Rent Income",
    "dashboard.totalDeposits": "Total Deposits",
    "dashboard.activeShops": "Active Shops",

    // Donations
    "donations.title": "Donations Management",
    "donations.addDonation": "Add Donation",
    "donations.donorName": "Donor Name",
    "donations.amount": "Amount",
    "donations.category": "Category",
    "donations.description": "Description",
    "donations.date": "Date",
    "donations.general": "General",
    "donations.birthday": "Birthday",
    "donations.marriage": "Marriage",
    "donations.festival": "Festival",
    "donations.festivalCollection": "Festival Collection",
    "donations.denagi": "Denagi (Donation)",
    "donations.governmentFunding": "Government Funding",
    "donations.galaDeposit": "Gala Deposit",
    "donations.galaBhade1": "Gala Bhade-1",
    "donations.galaBhade2": "Gala Bhade-2",
    "donations.governmentFundingGala": "Government Funding for Gala",
    // Main donation categories
    "donations.vargani": "Vargani (Festival Collection)",
    "donations.dengi": "Dengi (Donation)",
    "donations.shaskiyNighi": "Shaskiy Nidhi (Government Fund)",

    // Vargani sub-categories
    "donations.shivJayanti": "Shiv Jayanti",
    "donations.ganeshUtsav": "Ganesh Utsav",
    "donations.yatra": "Yatra",
    "donations.navratri": "Navratri",
    "donations.bailPola": "Bail Pola",
    "donations.ashadhiEkadashi": "Ashadhi Ekadashi",
    "donations.diwali": "Diwali",
    "donations.dasra": "Dasra",
    "donations.mahaShivratri": "Maha Shivratri",
    "donations.shreekrishnaJanmashtami": "ShreeKrushna Janmashtami",

    // Dengi sub-categories
    "donations.yatraUtsav": "Yatra Utsav",
    "donations.bandkam": "Bandkam (Construction)",
    "donations.itar": "Itar (Other)",

    // Government fund sub-categories
    "donations.kendraShashan": "Kendra Shashan (Central Government)",
    "donations.rajyaShashan": "Rajya Shashan (State Government)",
    "donations.mantriNidhi": "Mantri Nidhi (Minister Funding)",
    "donations.aamdarNidhi": "Aamdar Nidhi (MLA Funding)",
    "donations.khajdarNidhi": "Khajdar Nidhi (MP Funding)",
    "donations.grampanchayat": "Grampanchayat",
    "donations.panchayatSamiti": "Panchayat Samiti",

    // Form fields
    "donations.receiptNumber": "Receipt Number",
    "donations.subCategory": "Sub-Category",
    "donations.selectSubCategory": "Select Sub-Category",
    "donations.subCategoryRequired": "Sub-category is required",
    "donations.familyMembers": "Number of Family Members",
    "donations.enterFamilyMembers": "Enter number of family members",
    "donations.familyMembersRequired": "Number of family members is required",
    "donations.familyMembersInvalid":
      "Please enter a valid number of family members",
    "donations.amountPerPerson": "Amount per Person",
    "donations.enterAmountPerPerson": "Enter amount per person",
    "donations.amountPerPersonRequired": "Amount per person is required",
    "donations.amountPerPersonInvalid":
      "Please enter a valid amount per person",
    "donations.totalAmount": "Total Amount",
    "donations.purpose": "Purpose (Varnan)",
    "donations.enterPurpose": "Enter purpose of donation",
    "donations.purposeRequired": "Purpose is required",

    // Rent management categories
    "rent.bhadeJama": "Bhade Jama (Rent)",
    "rent.surakshaThev": "Suraksha Thev (Deposit)",
    "rent.bhade1Jama": "Bhade-1 Jama (Rent-1)",
    "rent.bhade2Jama": "Bhade-2 Jama (Rent-2)",
    "rent.rentShaskiyNidhi": "Shaskiy Nidhi (Government Fund)",

    // Rent form fields
    "rent.addRentIncome": "Add Rent Income",
    "rent.tenantName": "Tenant Name",
    "rent.enterTenantName": "Enter tenant name",
    "rent.tenantNameRequired": "Tenant name is required",
    "rent.tenantContact": "Tenant Contact",
    "rent.enterTenantContact": "Enter tenant contact",
    "rent.rentAmount": "Rent Amount",
    "rent.enterRentAmount": "Enter rent amount",
    "rent.rentAmountRequired": "Rent amount is required",
    "rent.rentAmountInvalid": "Please enter a valid rent amount",
    "rent.details": "Details (Varnan)",
    "rent.enterDetails": "Enter details",
    "rent.detailsRequired": "Details are required",
    "rent.successTitle": "Rent Income Added Successfully!",
    "rent.successMessage":
      "The rent income has been successfully added to the system.",
    "rent.rentDetails": "Rent Income Details",
    "rent.validationError":
      "Please fix the validation errors before submitting.",
    "rent.rentIncome": "Rent Income",
    "rent.useFormAbove": "Use the form above to add rent income transactions.",
    "rent.selectAgreement": "Select Agreement",
    "rent.agreementRequired": "Agreement selection is required",
    "rent.agreement": "Agreement",
    "rent.amountAutoPopulated":
      "Amount is automatically set based on agreement and sub-category",
    "rent.amountEditable": "Amount can be edited for Rent-2 payments",

    // Expense management categories
    "expenses.utsav": "Festivals",
    "expenses.galaKharch": "Shop Expenses",
    "expenses.mandirDekhbhal": "Temple Maintenance",

    // Festival sub-categories
    "expenses.parayan": "Parayan",
    "expenses.dindi": "Dindi",
    "expenses.shivjayanti": "Shiv Jayanti",
    "expenses.ganeshUtsav": "Ganesh Utsav",
    "expenses.yatra": "Yatra",
    "expenses.navratra": "Navratra",
    "expenses.bailPola": "Bail Pola",
    "expenses.ashadhiEkadashi": "Ashadhi Ekadashi",
    "expenses.diwali": "Diwali",
    "expenses.dasra": "Dasra",
    "expenses.mahashivratri": "Maha Shivratri",
    "expenses.shreeKrushnaJanmashtami": "Krishna Janmashtami",
    "expenses.ramNavami": "Ram Navami",

    // Shop expenses sub-categories
    "expenses.bandhkam": "Construction",
    "expenses.putalaKharch": "Statue Maintenance",
    "expenses.karmchariPagar": "Employee Salary",
    "expenses.karmchariKharch": "Employee Expenses",
    "expenses.safayi": "Cleaning",
    "expenses.bijliBill": "Electricity",
    "expenses.paani": "Water",
    "expenses.itar": "Other",

    // Temple maintenance sub-categories
    "expenses.pooja": "Pooja",
    "expenses.soundLightMaintenance": "Sound/Light System/CCTV/Electronic",
    "expenses.flowerDecoration": "Flower Decoration",
    "expenses.securityServices": "Security Services",

    // Expense form fields
    "expenses.payeeName": "Payee Name",
    "expenses.enterPayeeName": "Enter payee name",
    "expenses.payeeNameRequired": "Payee name is required",
    "expenses.payeeContact": "Payee Contact",
    "expenses.enterPayeeContact": "Enter payee contact number",
    "expenses.payeeContactInvalid":
      "Please enter a valid 10-digit phone number",
    "expenses.details": "Details",
    "expenses.enterDetails": "Enter expense details",
    "expenses.detailsRequired": "Details are required",
    "expenses.expenseSuccessTitle": "Expense Added Successfully!",
    "expenses.expenseSuccessMessage":
      "The expense has been successfully added to the system.",
    "expenses.expenseDetails": "Expense Details",
    "expenses.validationError":
      "Please fix the validation errors before submitting.",
    "donations.enterDonorName": "Enter donor name",
    "donations.enterAmount": "Enter amount",
    "donations.enterDescription": "Enter description",
    "donations.selectCategory": "Select category",
    "donations.shaskiynidhi": "Government Funding",
    "donations.submit": "Add Donation",
    "donations.dateRequired": "Date is required",
    "donations.categoryRequired": "Category is required",
    "donations.amountRequired": "Amount is required",
    "donations.amountInvalid": "Please enter a valid amount",
    "donations.descriptionRequired": "Description is required",
    "donations.donorNameInvalid": "Donor name must be at least 2 characters",
    "donations.donorContactInvalid":
      "Please enter a valid 10-digit mobile number",
    "donations.validationError": "Please fix the errors in the form",
    "donations.successTitle": "Donation Added Successfully!",
    "donations.successMessage":
      "Thank you for your contribution. The donation has been recorded.",
    "donations.donationDetails": "Donation Details",
    "donations.donorContact": "Donor Contact",
    "donations.enterDonorContact": "Enter donor contact number",
    "donations.denagiDonorName": "Donor Name",
    "donations.denagiDonorContact": "Donor Contact",
    "donations.enterDenagiDonorName": "Enter donor name",
    "donations.enterDenagiDonorContact": "Enter donor contact number",
    "donations.editDonation": "Edit Donation",
    "donations.updateSuccessMessage": "Donation updated successfully!",
    "donations.submitting": "Submitting...",
    "donations.duplicateDetected": "Donation was already submitted successfully!",
    "donations.duplicateSubmission": "This donation has already been submitted. Please refresh and try again.",
    "donations.receiptNumberConflict": "Receipt number conflict detected. A new receipt number has been assigned.",
    "donations.conflictError": "A conflict occurred while submitting the donation. Please try again.",
    "donations.nextReceiptNumber": "(Next Available)",
    "donations.autoGenerated": "Auto-generated",

    // Expenses
    "expenses.title": "Expenses Management",
    "expenses.addExpense": "Add Expense",
    "expenses.expenseType": "Expense Type",
    "expenses.maintenance": "Maintenance",
    "expenses.utilities": "Utilities",
    "expenses.salary": "Salary",
    "expenses.supplies": "Supplies",
    "expenses.other": "Other",
    "expenses.parayana": "Parayana",
    "expenses.shivJayanti": "Shiv Jayanti",
    "expenses.ganpatiUtsav": "Ganpati Utsav",
    "expenses.cleaning": "Cleaning",
    "expenses.miscellaneous": "Miscellaneous Expenses",
    "expenses.enterExpenseType": "Enter expense type",
    "expenses.submit": "Add Expense",
    "expenses.vendor": "Vendor/Payee",
    "expenses.enterVendor": "Enter vendor or payee name",
    "expenses.receiptNumber": "Receipt Number",
    "expenses.enterReceiptNumber": "Enter receipt number",
    "expenses.vendorInvalid": "Vendor name must be at least 2 characters",
    "expenses.receiptInvalid": "Receipt number must be at least 3 characters",
    "expenses.successTitle": "Expense Added Successfully!",
    "expenses.successMessage": "The expense has been recorded in the system.",
    "expenses.editExpense": "Edit Expense",
    "expenses.updateSuccessMessage": "Expense updated successfully!",

    // Reports
    "reports.title": "Financial Reports",
    "reports.overview": "Financial Overview",
    "reports.monthlyTrend": "Monthly Trend",
    "reports.categoryBreakdown": "Category Breakdown",
    "reports.totalTransactions": "Total Transactions",
    "reports.averageTransaction": "Average Transaction",
    "reports.month": "Month",
    "reports.donations": "Donations",
    "reports.expenses": "Expenses",
    "reports.export": "Export",
    "reports.import": "Import",
    "reports.exportData": "Export Data",
    "reports.importData": "Import Data",
    "reports.exportTransactions": "Export Transactions",
    "reports.exportSummary": "Export Summary",
    "reports.exportCategorySummary": "Export Category Summary",
    "reports.importTransactions": "Import Transactions",
    "reports.selectDateRange": "Select Date Range",
    "reports.fromDate": "From Date",
    "reports.toDate": "To Date",
    "reports.selectTransactionType": "Select Transaction Type",
    "reports.allTransactions": "All Transactions",
    "reports.donationsOnly": "Donations Only",
    "reports.expensesOnly": "Expenses Only",
    "reports.rentIncomeOnly": "Rent Income Only",
    "reports.downloadCSV": "Download CSV",
    "reports.downloadPDF": "Download PDF",
    "reports.uploadCSV": "Upload CSV File",
    "reports.selectFile": "Select File",
    "reports.fileFormat": "File Format",
    "reports.csvFormat":
      "CSV format with columns: Date, Type, Category, Description, Amount",
    "reports.sampleFormat":
      "Sample: 2024-01-15,Donation,General,Temple donation,5000",
    "reports.fileSelected": "File Selected",
    "reports.noFileSelected": "No file selected",
    "reports.importSuccess": "Data imported successfully",
    "reports.importError": "Error importing data",
    "reports.invalidFormat": "Invalid file format",
    "reports.validationError": "Data validation failed",
    "reports.processingImport": "Processing import...",
    "reports.exportSuccess": "Data exported successfully",
    "reports.exportError": "Error exporting data",
    "reports.generating": "Generating report...",
    "reports.generatingPDF": "Generating PDF...",
    "reports.pdfLanguage": "PDF Language",
    "reports.selectPDFLanguage": "Select PDF Language",
    "reports.englishPDF": "English PDF",
    "reports.marathiPDF": "Marathi PDF",
    "reports.financialReport": "Financial Report",
    "reports.generatedOn": "Generated On",
    "reports.period": "Period",
    "reports.srNo": "Sr. No.",
    "reports.totalAmount": "Total Amount",
    "reports.transactionReport": "Transaction Report",
    "reports.summaryReport": "Summary Report",
    "reports.categoryReport": "Category Report",
    "reports.monthlyReport": "Monthly Report",
    "reports.filters": "Filters",
    "reports.clearFilters": "Clear Filters",
    "reports.applyFilters": "Apply Filters",
    "reports.filterByType": "Filter by Type",
    "reports.filterByCategory": "Filter by Category",
    "reports.filterBySubCategory": "Filter by Sub-Category",
    "reports.filterByMonth": "Filter by Month",
    "reports.filterByDateRange": "Filter by Date Range",
    "reports.selectCategory": "Select Category",
    "reports.selectSubCategory": "Select Sub-Category",
    "reports.selectMonth": "Select Month",
    "reports.selectYear": "Select Year",
    "reports.noFiltersApplied": "No filters applied",
    "reports.filteredResults": "Filtered Results",
    "reports.showingResults": "Showing {count} of {total} transactions",
    "reports.noTransactionsFound":
      "No transactions found matching the selected filters",
    "reports.allTypes": "All Types",
    "reports.allCategories": "All Categories",
    "reports.allSubCategories": "All Sub-Categories",
    "reports.allMonths": "All Months",
    "reports.viewMode": "View Mode",
    "reports.tableView": "Table View",
    "reports.summaryView": "Summary View",

    // Loan Management
    "loans.title": "Loan Management",
    "loans.addLoan": "Add New Loan",
    "loans.loanDetails": "Loan Details",
    "loans.loanAmount": "Loan Amount",
    "loans.enterLoanAmount": "Enter loan amount",
    "loans.interestRate": "Interest Rate (%)",
    "loans.enterInterestRate": "Enter monthly interest rate",
    "loans.loanDuration": "Loan Duration (Months)",
    "loans.enterLoanDuration": "Enter loan duration in months",
    "loans.disbursedDate": "Disbursed Date",
    "loans.monthlyEmi": "Monthly EMI",
    "loans.outstandingBalance": "Outstanding Balance",
    "loans.totalRepaid": "Total Repaid",
    "loans.nextEmiDate": "Next EMI Date",
    "loans.lastPaymentDate": "Last Payment Date",
    "loans.loanStatus": "Loan Status",
    "loans.activeLoan": "Active",
    "loans.completedLoan": "Completed",
    "loans.defaultedLoan": "Defaulted",
    "loans.selectTenant": "Select Tenant",
    "loans.selectAgreement": "Select Agreement",
    "loans.loanAmountRequired": "Loan amount is required",
    "loans.loanAmountInvalid": "Please enter a valid loan amount",
    "loans.interestRateRequired": "Interest rate is required",
    "loans.interestRateInvalid": "Please enter a valid interest rate",
    "loans.loanDurationRequired": "Loan duration is required",
    "loans.loanDurationInvalid": "Please enter a valid loan duration",
    "loans.tenantRequired": "Tenant selection is required",
    "loans.agreementRequired": "Agreement selection is required",
    "loans.disbursedDateRequired": "Disbursed date is required",
    "loans.successTitle": "Loan Added Successfully!",
    "loans.successMessage":
      "The loan has been successfully added to the system.",
    "loans.validationError":
      "Please fix the validation errors before submitting.",
    "loans.emiPayment": "EMI Payment",
    "loans.payEmi": "Pay EMI",
    "loans.calculateEmi": "Calculate EMI",
    "loans.loanAgreement": "Loan Agreement",
    "loans.uploadLoanAgreement": "Upload Loan Agreement",

    // Penalty Management
    "penalties.title": "Penalty Management",
    "penalties.addPenalty": "Add Penalty",
    "penalties.penaltyDetails": "Penalty Details",
    "penalties.rentAmount": "Rent Amount",
    "penalties.dueDate": "Due Date",
    "penalties.paidDate": "Paid Date",
    "penalties.penaltyRate": "Penalty Rate (%)",
    "penalties.penaltyAmount": "Penalty Amount",
    "penalties.penaltyStatus": "Penalty Status",
    "penalties.pendingPenalty": "Pending",
    "penalties.paidPenalty": "Paid",
    "penalties.penaltyPaid": "Penalty Paid",
    "penalties.penaltyPaidDate": "Penalty Paid Date",
    "penalties.calculatePenalty": "Calculate Penalty",
    "penalties.payPenalty": "Pay Penalty",
    "penalties.lateFee": "Late Fee",
    "penalties.overdueRent": "Overdue Rent",
    "penalties.automaticPenalty": "Automatic penalty applied for late payment",
    "penalties.penaltyCalculation":
      "Penalty = Rent Amount × Penalty Rate × Delay Days / 30",

    // Shop Management
    "shop.title": "Shop Management",
    "shop.addShop": "Add New Shop",
    "shop.shopDetails": "Shop Details",
    "shop.shopNumber": "Shop Number",
    "shop.enterShopNumber": "Enter shop number",
    "shop.shopSize": "Shop Size (sq ft)",
    "shop.enterShopSize": "Enter shop size",
    "shop.monthlyRent": "Monthly Rent",
    "shop.enterMonthlyRent": "Enter monthly rent",
    "shop.securityDeposit": "Security Deposit",
    "shop.enterSecurityDeposit": "Enter security deposit",
    "shop.shopDescription": "Description",
    "shop.enterShopDescription": "Enter shop description",
    "shop.shopStatus": "Shop Status",
    "shop.vacant": "Vacant",
    "shop.occupied": "Occupied",
    "shop.maintenance": "Under Maintenance",
    "shop.shopNumberRequired": "Shop number is required",
    "shop.shopSizeRequired": "Shop size is required",
    "shop.shopSizeInvalid": "Please enter a valid shop size",
    "shop.monthlyRentRequired": "Monthly rent is required",
    "shop.monthlyRentInvalid": "Please enter a valid monthly rent",
    "shop.securityDepositRequired": "Security deposit is required",
    "shop.securityDepositInvalid": "Please enter a valid security deposit",
    "shop.successTitle": "Shop Added Successfully!",
    "shop.successMessage":
      "The shop has been successfully added to the system.",
    "shop.validationError":
      "Please fix the validation errors before submitting.",
    "shop.shopAdded": "Shop added successfully",
    "shop.shopUpdated": "Shop updated successfully",
    "shop.shopDeleted": "Shop deleted successfully",
    "shop.cannotDeleteOccupiedShop": "Cannot delete occupied shop",
    "shop.editShop": "Edit Shop",
    "shop.deleteShop": "Delete Shop",

    // Tenant Management
    "tenant.title": "Tenant Management",
    "tenant.addTenant": "Add New Tenant",
    "tenant.tenantDetails": "Tenant Details",
    "tenant.tenantName": "Tenant Name",
    "tenant.enterTenantName": "Enter tenant name",
    "tenant.tenantPhone": "Phone Number",
    "tenant.enterTenantPhone": "Enter phone number",
    "tenant.tenantEmail": "Email Address",
    "tenant.enterTenantEmail": "Enter email address",
    "tenant.tenantAddress": "Address",
    "tenant.enterTenantAddress": "Enter complete address",
    "tenant.businessType": "Business Type",
    "tenant.enterBusinessType": "Enter type of business",
    "tenant.idProof": "ID Proof Details",
    "tenant.enterIdProof": "Enter ID proof details (Aadhaar/PAN/etc.)",
    "tenant.tenantStatus": "Tenant Status",
    "tenant.tenantNameRequired": "Tenant name is required",
    "tenant.tenantNameInvalid": "Tenant name must be at least 2 characters",
    "tenant.tenantPhoneRequired": "Phone number is required",
    "tenant.tenantPhoneInvalid": "Please enter a valid 10-digit phone number",
    "tenant.tenantEmailInvalid": "Please enter a valid email address",
    "tenant.tenantAddressRequired": "Address is required",
    "tenant.businessTypeRequired": "Business type is required",
    "tenant.successTitle": "Tenant Added Successfully!",
    "tenant.successMessage":
      "The tenant has been successfully added to the system.",
    "tenant.validationError":
      "Please fix the validation errors before submitting.",
    "tenant.tenantAdded": "Tenant added successfully",
    "tenant.tenantUpdated": "Tenant updated successfully",
    "tenant.tenantDeleted": "Tenant deleted successfully",
    "tenant.cannotDeleteTenantWithActiveAgreements":
      "Cannot delete tenant with active agreements",
    "tenant.editTenant": "Edit Tenant",
    "tenant.deleteTenant": "Delete Tenant",

    // Agreement Management
    "agreement.title": "Agreement Management",
    "agreement.createAgreement": "Create New Agreement",
    "agreement.agreementDetails": "Agreement Details",
    "agreement.selectShop": "Select Shop",
    "agreement.selectTenant": "Select Tenant",
    "agreement.agreementDate": "Agreement Date",
    "agreement.agreementDuration": "Duration (Months)",
    "agreement.enterDuration": "Enter duration in months",
    "agreement.agreementType": "Agreement Type",
    "agreement.residential": "Residential",
    "agreement.commercial": "Commercial",
    "agreement.advanceRent": "Advance Rent",
    "agreement.enterAdvanceRent": "Enter advance rent amount",
    "agreement.totalDeposit": "Total Deposit",
    "agreement.shopRequired": "Shop selection is required",
    "agreement.tenantRequired": "Tenant selection is required",
    "agreement.agreementDateRequired": "Agreement date is required",
    "agreement.durationRequired": "Duration is required",
    "agreement.durationInvalid": "Please enter a valid duration",
    "agreement.securityDepositRequired": "Security deposit is required",
    "agreement.securityDepositInvalid": "Please enter a valid security deposit",
    "agreement.advanceRentRequired": "Advance rent is required",
    "agreement.advanceRentInvalid": "Please enter a valid advance rent",
    "agreement.successTitle": "Agreement Created Successfully!",
    "agreement.successMessage":
      "The rental agreement has been successfully created.",
    "agreement.validationError":
      "Please fix the validation errors before submitting.",
    "agreement.agreementCreated": "Agreement created successfully",
    "agreement.agreementUpdated": "Agreement updated successfully",
    "agreement.uploadAgreementDocument": "Upload Agreement Document",
    "agreement.agreementDocument": "Agreement Document",
    "agreement.activeAgreements": "Active Agreements",
    "agreement.viewAgreement": "View Agreement",
    "agreement.editAgreement": "Edit Agreement",
    "agreement.terminateAgreement": "Terminate Agreement",
    "agreement.renewAgreement": "Renew Agreement",
    "agreement.expiredAgreements": "Expired Agreements",
    "agreement.terminatedAgreements": "Terminated Agreements",

    // Enhanced Rent Management
    "rent.title": "Rent Management",
    "rent.shopManagement": "Shop Management",
    "rent.tenantManagement": "Tenant Management",
    "rent.agreements": "Agreements",
    "rent.rentCollection": "Rent Collection",
    "rent.addShop": "Add Shop",
    "rent.addTenant": "Add Tenant",
    "rent.createAgreement": "Create Agreement",
    "rent.collectRent": "Collect Rent",
    "rent.shopNumber": "Shop Number",
    "rent.shopSize": "Shop Size",
    "rent.monthlyRent": "Monthly Rent",
    "rent.deposit": "Deposit",
    "rent.status": "Status",
    "rent.vacant": "Vacant",
    "rent.occupied": "Occupied",
    "rent.maintenance": "Maintenance",
    "rent.tenantPhone": "Tenant Phone",
    "rent.tenantEmail": "Tenant Email",
    "rent.tenantAddress": "Tenant Address",
    "rent.businessType": "Business Type",
    "rent.agreementDate": "Agreement Date",
    "rent.agreementDuration": "Agreement Duration",
    "rent.rentDueDate": "Rent Due Date",
    "rent.lastPayment": "Last Payment",
    "rent.nextDue": "Next Due",
    "rent.overdue": "Overdue",
    "rent.paid": "Paid",
    "rent.pending": "Pending",
    "rent.agreementDetails": "Agreement Details",
    "rent.depositAmount": "Deposit Amount",
    "rent.securityDeposit": "Security Deposit",
    "rent.advanceRent": "Advance Rent",
    "rent.totalDeposit": "Total Deposit",
    "rent.agreementType": "Agreement Type",
    "rent.residential": "Residential",
    "rent.commercial": "Commercial",
    "rent.paymentHistory": "Payment History",
    "rent.enterShopNumber": "Enter shop number",
    "rent.enterShopSize": "Enter shop size (sq ft)",
    "rent.enterMonthlyRent": "Enter monthly rent",
    "rent.enterDeposit": "Enter deposit amount",
    "rent.enterTenantPhone": "Enter tenant phone",
    "rent.enterTenantEmail": "Enter tenant email",
    "rent.enterTenantAddress": "Enter tenant address",
    "rent.enterBusinessType": "Enter business type",
    "rent.selectShop": "Select shop",
    "rent.selectTenant": "Select tenant",
    "rent.selectAgreementType": "Select agreement type",
    "rent.agreementGenerated": "Agreement Generated Successfully",
    "rent.rentCollected": "Rent Collected Successfully",
    "rent.months": "months",
    "rent.years": "years",
    "rent.sqft": "sq ft",
    "rent.generateAgreement": "Generate Agreement",
    "rent.viewAgreement": "View Agreement",
    "rent.printAgreement": "Print Agreement",
    "rent.renewAgreement": "Renew Agreement",
    "rent.terminateAgreement": "Terminate Agreement",
    "rent.loanManagement": "Loan Management",
    "rent.penaltyManagement": "Penalty Management",
    "rent.activeLoans": "Active Loans",
    "rent.pendingPenalties": "Pending Penalties",
    "rent.collectRentWithLoan": "Collect Rent with Loan/Penalty",
    "rent.rentAndEmiCollection": "Rent & EMI Collection",
    "rent.emiAmount": "EMI Amount",
    "rent.penaltyCollection": "Penalty Collection",
    "rent.totalCollection": "Total Collection",
    "rent.rentCollectionSuccess": "Rent/EMI/Penalty collected successfully",
    "rent.noActiveLoans": "No active loans found",
    "rent.noPendingPenalties": "No pending penalties found",

    // User Management
    "users.title": "User Management",
    "users.addUser": "Add User",
    "users.addNewUser": "Add New User",
    "users.editUser": "Edit User",
    "users.username": "Username",
    "users.email": "Email",
    "users.role": "Role",
    "users.status": "Status",
    "users.lastLogin": "Last Login",
    "users.actions": "Actions",
    "users.admin": "Admin",
    "users.treasurer": "Treasurer",
    "users.viewer": "Viewer",
    "users.active": "Active",
    "users.inactive": "Inactive",
    "users.never": "Never",
    "users.createAccount":
      "Create a new user account for the temple management system.",
    "users.updateInfo": "Update user information and permissions.",
    "users.updateUser": "Update User",
    "users.rolePermissions": "Role Permissions:",
    "users.adminDesc": "Full access to all features including user management",
    "users.treasurerDesc": "Can manage donations and expenses",
    "users.viewerDesc": "Can only view reports and dashboard",

    // Common
    "common.actions": "Actions",
    "common.edit": "Edit",
    "common.delete": "Delete",
    "common.cancel": "Cancel",
    "common.save": "Save",
    "common.close": "Close",
    "common.submit": "Submit",
    "common.update": "Update",
    "common.confirmDelete": "Are you sure you want to delete this item? This action cannot be undone.",
    "common.loading": "Loading...",
    "common.search": "Search",
    "common.filter": "Filter",
    "common.export": "Export",
    "common.import": "Import",
    "common.type": "Type",
    "common.amount": "Amount",
    "common.date": "Date",
    "common.description": "Description",
    "common.total": "Total",
    "common.currency": "₹",
    "common.noPermission":
      "You don't have permission to access this section. Please contact your administrator.",
    "common.view": "View",
    "common.print": "Print",
    "common.download": "Download",
    "common.upload": "Upload",
    "common.select": "Select",
    "common.all": "All",
    "common.none": "None",
    "common.add": "Add",
    "common.create": "Create",
    "common.name": "Name",
    "common.phone": "Phone",
    "common.email": "Email",
    "common.address": "Address",
    "common.success": "Success",
    "common.error": "Error",
    "common.warning": "Warning",
    "common.info": "Information",
    "common.pickDate": "Pick a date",

    // Language
    "language.english": "English",
    "language.marathi": "मराठी",
    "language.switch": "Switch Language",

    // Document upload translations
    "documents.upload": "Upload Documents",
    "documents.receiptImage": "Receipt/Bill Image",
    "documents.agreementDocument": "Agreement Document",
    "documents.supportingDocuments": "Supporting Documents",
    "documents.uploadReceiptImage": "Upload Receipt/Bill Image",
    "documents.uploadAgreementDocument": "Upload Agreement Document",
    "documents.uploadSupportingDocuments": "Upload Supporting Documents",
    "documents.dragAndDrop": "Click to upload or drag and drop",
    "documents.fileLimit": "Maximum 5 files, 300KB each",
    "documents.supportedFormats": "Supports JPG, PNG, PDF",
    "documents.uploadSuccess": "Document uploaded successfully",
    "documents.uploadError": "Failed to upload document",
    "documents.fileSizeError": "File size exceeds limit",
    "documents.fileTypeError": "File type not supported",
    "documents.maxFilesError": "Maximum files limit reached",
    "documents.viewDocument": "View Document",
    "documents.downloadDocument": "Download Document",
    "documents.removeDocument": "Remove Document",
    "documents.noPreview": "Preview not available",
    "documents.downloadToView": "Download to View",
  },
  mr: {
    // Header
    "header.title": "श्री क्षेत्र खंडेश्वर देवस्थान कुसळंब",
    "header.titleMarathi": "श्री क्षेत्र खंडेश्वर देवस्थान कुसळंब",
    "header.subtitle": "मंदिर व्यवस्थापन प्रणाली",
    "header.subtitleMarathi": "मंदिर व्यवस्थापन प्रणाली",
    "nav.dashboard": "डॅशबोर्ड",
    "nav.donations": "जमा",
    "nav.expenses": "खर्च",
    "nav.reports": "अहवाल",
    "nav.users": "वापरकर्ते",
    "nav.rentManagement": "भाडे व्यवस्थापन",
    "user.settings": "सेटिंग्स",
    "user.userManagement": "वापरकर्ता व्यवस्थापन",
    "user.logout": "बाहेर पडा",
    "user.signedInAs": "या नावे साइन इन केले",

    // Login
    "login.welcome": "स्वागत",
    "login.username": "वापरकर्ता नाव",
    "login.password": "संकेतशब्द",
    "login.signIn": "साइन इन करा",
    "login.signingIn": "साइन इन करत आहे...",
    "login.enterUsername": "आपले वापरकर्ता नाव टाका",
    "login.enterPassword": "आपला संकेतशब्द टाका",
    "login.demoCredentials": "डेमो क्रेडेंशियल्स:",
    "login.invalidCredentials":
      "चुकीचे वापरकर्ता नाव किंवा संकेतशब्द, किंवा खाते निष्क्रिय",

    // Authentication
    "auth.loading": "लोड होत आहे...",

    // Dashboard
    "dashboard.title": "डॅशबोर्ड",
    "dashboard.totalDonations": "एकूण जमा",
    "dashboard.totalExpenses": "एकूण खर्च",
    "dashboard.netBalance": "निव्वळ शिल्लक",
    "dashboard.recentTransactions": "अलीकडील व्यवहार",
    "dashboard.viewAll": "सर्व पहा",
    "dashboard.totalRentIncome": "एकूण भाडे उ���्पन्न",
    "dashboard.totalDeposits": "एकूण ठेवी",
    "dashboard.activeShops": "सक्���िय दुकाने",

    // Donations
    "donations.title": "जमा व्यवस्थापन",
    "donations.addDonation": "जमा जोडा",
    "donations.donorName": "वर्गणी धारकाचे नाव",
    "donations.amount": "रक्कम",
    "donations.category": "श्रेणी",
    "donations.description": "वर्णन",
    "donations.date": "दिनांक",
    "donations.general": "सामान्य",
    "donations.birthday": "वाढदिवस",
    "donations.marriage": "लग्न",
    "donations.festival": "सण",
    "donations.festivalCollection": "वर्गणी",
    "donations.denagi": "देणगी",
    "donations.governmentFunding": "सरकारी अनुदान",
    "donations.galaDeposit": "गाळा ठेव",
    "donations.galaBhade1": "गाळा भाडे-1",
    "donations.galaBhade2": "गाळा भाडे-2",
    "donations.governmentFundingGala": "गाल्यासाठी सरकारी अनुदान",
    // Main donation categories
    "donations.vargani": "वर्गणी",
    "donations.dengi": "देणगी",
    "donations.shaskiyNighi": "शासकीय निधी",

    // Vargani sub-categories
    "donations.shivJayanti": "शिव जयंती",
    "donations.ganeshUtsav": "गणेश उत्सव",
    "donations.yatra": "यात्रा",
    "donations.navratri": "नवरात्र",
    "donations.bailPola": "बैल पोळा",
    "donations.ashadhiEkadashi": "आषाढी एकादशी",
    "donations.diwali": "दिवाळी",
    "donations.dasra": "दसरा",
    "donations.mahaShivratri": "महाशिवरात्री",
    "donations.shreekrishnaJanmashtami": "श्रीकृष्ण जन्माष्टमी",

    // Dengi sub-categories
    "donations.yatraUtsav": "यात्रा उत्सव",
    "donations.bandkam": "बांधकाम",
    "donations.itar": "इतर",

    // Government fund sub-categories
    "donations.kendraShashan": "केंद्र शासन",
    "donations.rajyaShashan": "राज्य शासन",
    "donations.mantriNidhi": "मंत्री निधी",
    "donations.aamdarNidhi": "आमदार निधी",
    "donations.khajdarNidhi": "खासदार निधी",
    "donations.grampanchayat": "ग्रामपंचायत",
    "donations.panchayatSamiti": "पंचायत समिती",

    // Form fields
    "donations.receiptNumber": "पावती क्रमांक",
    "donations.subCategory": "उप-श्रेणी",
    "donations.selectSubCategory": "उप-श्रेणी निवडा",
    "donations.subCategoryRequired": "उप-श्रेणी आवश्यक आहे",
    "donations.familyMembers": "कुटुंबातील सदस्य संख्या",
    "donations.enterFamilyMembers": "कुटुंबातील सदस्य संख्या प्रविष्ट करा",
    "donations.familyMembersRequired": "कुटुंबातील सदस्य संख्या आवश्यक आहे",
    "donations.familyMembersInvalid": "कृपया वैध सदस्य संख्या प्रविष्ट करा",
    "donations.amountPerPerson": "प्रति व्यक्ती रक्कम",
    "donations.enterAmountPerPerson": "प्रति व्यक्ती रक्कम प्रविष्ट करा",
    "donations.amountPerPersonRequired": "प्रति व्यक्ती रक्कम आवश्यक आहे",
    "donations.amountPerPersonInvalid":
      "कृपया वैध प्रति व्यक्ती रक्कम प्रविष्ट करा",
    "donations.totalAmount": "एकूण रक्कम",
    "donations.purpose": "शेरा",
    "donations.enterPurpose": "देणगीचा हेतू प्रविष्ट करा",
    "donations.purposeRequired": "हेतू आवश्यक आहे",

    // Rent management categories
    "rent.bhadeJama": "भाडे जमा",
    "rent.surakshaThev": "सुरक्षा ठेव",
    "rent.bhade1Jama": "भाडे-1 जमा",
    "rent.bhade2Jama": "भाडे-2 जमा",
    "rent.rentShaskiyNidhi": "शासकीय निधी",

    // Rent form fields
    "rent.addRentIncome": "भाडे उत्पन्न जोडा",
    "rent.tenantName": "भाडेकरूचे नाव",
    "rent.enterTenantName": "भाडेकरूचे नाव प्रविष्ट करा",
    "rent.tenantNameRequired": "भाडेकरूचे नाव आवश्यक आहे",
    "rent.tenantContact": "भाडेकरूचा संपर्क",
    "rent.enterTenantContact": "भाडेकरूचा संपर्क प्रविष्ट करा",
    "rent.rentAmount": "भाडे रक्कम",
    "rent.enterRentAmount": "भाडे रक्कम प्रविष्ट करा",
    "rent.rentAmountRequired": "भाडे रक्कम आवश्यक आहे",
    "rent.rentAmountInvalid": "कृपया वैध भाडे रक्कम प्रविष्ट करा",
    "rent.details": "शेरा",
    "rent.enterDetails": "शेरा प्रविष्ट करा",
    "rent.detailsRequired": "शेरा आवश्यक आहे",
    "rent.successTitle": "भाडे उत्पन्न यशस्वीरित्या जोडले गेले!",
    "rent.successMessage":
      "भाडे उत्पन्न यशस्वीरित्या सिस्टममध्ये जोडले गेले आहे.",
    "rent.rentDetails": "भाडे उत्पन्नाचे तपशील",
    "rent.validationError":
      "कृपया सबमिट करण्यापूर्वी वैधता त्रुटी दुरुस्त करा.",
    "rent.rentIncome": "भाडे उत्पन्न",
    "rent.useFormAbove": "भाडे उत्पन्न व्यवहार जोडण्यासाठी वरील फॉर्म वापरा.",
    "rent.selectAgreement": "करार निवडा",
    "rent.agreementRequired": "करार निवड आवश्यक आहे",
    "rent.agreement": "करार",
    "rent.amountAutoPopulated":
      "रक्कम करार आणि उप-श्रेणीच्या आधारावर आपोआप सेट केली जाते",
    "rent.amountEditable": "भाडे-2 पेमेंटसाठी रक्कम संपादित करता येते",

    // Expense management categories
    "expenses.utsav": "उत्सव",
    "expenses.galaKharch": "गाळा खर्च",
    "expenses.mandirDekhbhal": "मंदिर खर्च",

    // Festival sub-categories
    "expenses.parayan": "पारायण",
    "expenses.dindi": "दिंडी",
    "expenses.shivjayanti": "शिवजयंती",
    "expenses.ganeshUtsav": "गणेश उत्सव",
    "expenses.yatra": "यात्रा",
    "expenses.navratra": "नवरात्र",
    "expenses.bailPola": "बैल पोळा",
    "expenses.ashadhiEkadashi": "आषाढी एकादशी",
    "expenses.diwali": "दिवाळी",
    "expenses.dasra": "दसरा",
    "expenses.mahashivratri": "महाशिवरात्री",
    "expenses.shreeKrushnaJanmashtami": "कृष्ण जन्माष्टमी",
    "expenses.ramNavami": "राम नवमी",

    // Shop expenses sub-categories
    "expenses.bandhkam": "बांधकाम",
    "expenses.putalaKharch": "पुतळा देखभाल",
    "expenses.karmchariPagar": "कर्मचारी पगार",
    "expenses.karmchariKharch": "कर्मचारी खर्च",
    "expenses.safayi": "सफाई",
    "expenses.bijliBill": "वीज",
    "expenses.paani": "पाणी",
    "expenses.itar": "इतर",

    // Temple maintenance sub-categories
    "expenses.pooja": "पूजा",
    "expenses.soundLightMaintenance": "ध्वनी/प्रकाश/सीसीटीव्ही/इलेक्ट्रॉनिक",
    "expenses.flowerDecoration": "फुलसजावट",
    "expenses.securityServices": "सुरक्षा सेवा",

    // Expense form fields
    "expenses.payeeName": "धारक नाव",
    "expenses.enterPayeeName": "धारकाचे नाव प्रविष्ट करा",
    "expenses.payeeNameRequired": "धारकाचे नाव आवश्यक आहे",
    "expenses.payeeContact": "धारक संपर्क",
    "expenses.enterPayeeContact": "धारकाचा संपर्क नंबर प्रविष्ट करा",
    "expenses.payeeContactInvalid": "कृपया वैध 10-अंकी फोन नंबर प्रविष्ट करा",
    "expenses.details": "शेरा",
    "expenses.enterDetails": "खर्चाचे तपशील प्रविष्ट करा",
    "expenses.detailsRequired": "शेरा आवश्यक आहे",
    "expenses.expenseSuccessTitle": "खर्च यशस्वीरित्या जोडला गेला!",
    "expenses.expenseSuccessMessage":
      "खर्च यशस्वीरित्या सिस्टममध्ये जोडला गेला आहे.",
    "expenses.expenseDetails": "खर्चाचे तपशील",
    "expenses.validationError":
      "क���पया सबमिट करण्यापूर्वी वैधता त्रुटी दुरुस्त करा.",
    "donations.enterDonorName": "वर्गणी धारकाचे नाव टाका",
    "donations.enterAmount": "रक्कम टाका",
    "donations.enterDescription": "शेरा टाका",
    "donations.selectCategory": "श्रेणी निवडा",
    "donations.shaskiynidhi": "शासकीय निधी",
    "donations.submit": "जमा जोडा",
    "donations.dateRequired": "दिनांक आवश्यक आहे",
    "donations.categoryRequired": "श्रेणी आवश्यक आहे",
    "donations.amountRequired": "रक्कम आवश्यक आहे",
    "donations.amountInvalid": "कृपया योग्य रक्कम टाका",
    "donations.descriptionRequired": "शेरा आवश्यक आहे",
    "donations.donorNameInvalid": "वर्गणी धारकाचे नाव किमान 2 अक्षरांचे असावे",
    "donations.donorContactInvalid": "कृपया योग्य 10 अंकी मोबाइल नंबर टाका",
    "donations.validationError": "कृपया फॉर्ममधील त्रुटी दुरुस्त करा",
    "donations.successTitle": "जमा यशस्वीरित्या जोडला गेला!",
    "donations.successMessage":
      "आपल्या योगदानाबद्दल धन्यवाद. जमा नोंदविला गेला आहे.",
    "donations.donationDetails": "जमा तपशील",
    "donations.donorContact": "वर्गणी धारकाचा संपर्क",
    "donations.enterDonorContact": "वर्गणी धारकाचा संपर्क क्रमांक टाका",
    "donations.denagiDonorName": "देणगी धारकाचे नाव",
    "donations.denagiDonorContact": "देणगी धारकाचा संपर्क",
    "donations.enterDenagiDonorName": "देणगी धारकाचे नाव टाका",
    "donations.enterDenagiDonorContact": "देणगी धारकाचा संपर्क क्रमांक टाका",
    "donations.editDonation": "जमा संपादित करा",
    "donations.updateSuccessMessage": "जमा यशस्वीरित्या अपडेट झाला!",

    // Expenses
    "expenses.title": "खर्च व्यवस्थापन",
    "expenses.addExpense": "खर्च जोडा",
    "expenses.expenseType": "खर्चाचा प्रकार",
    "expenses.maintenance": "देखभाल",
    "expenses.utilities": "उपयोगिता",
    "expenses.salary": "पगार",
    "expenses.supplies": "पुरवठा",
    "expenses.other": "इतर",
    "expenses.parayana": "पारायण",
    "expenses.shivJayanti": "शिव जयंती",
    "expenses.ganpatiUtsav": "गणपती उत्सव",
    "expenses.cleaning": "साफसफाई",
    "expenses.miscellaneous": "विविध खर्च",
    "expenses.enterExpenseType": "खर्चाचा प्रकार टाका",
    "expenses.submit": "खर्च जोडा",
    "expenses.vendor": "विक्रेता/प्राप्तकर्ता",
    "expenses.enterVendor": "विक्रेता किंवा प्राप्तकर्त्याचे नाव टाका",
    "expenses.receiptNumber": "पावती क्रमांक",
    "expenses.enterReceiptNumber": "पावती क्रमांक टाका",
    "expenses.vendorInvalid": "विक्रेत्याचे नाव किमान 2 अक्षरांचे असावे",
    "expenses.receiptInvalid": "पावती क्रमांक किमान 3 अक्षरांचा असावा",
    "expenses.successTitle": "खर्च यशस्वीरित्या जोडला गेला!",
    "expenses.successMessage": "खर्च सिस्टममध्ये नोंदविला गेला आहे.",
    "expenses.editExpense": "खर्च संपादित करा",
    "expenses.updateSuccessMessage": "खर्च यशस्वीरित्या अपडेट झाला!",

    // Reports
    "reports.title": "आर्थिक अहवाल",
    "reports.overview": "आर्थिक सारांश",
    "reports.monthlyTrend": "मासिक प्रवृत्ती",
    "reports.categoryBreakdown": "श्रेणी विभाजन",
    "reports.totalTransactions": "एकूण व्यवहार",
    "reports.averageTransaction": "सरासरी व्यवहार",
    "reports.month": "महिना",
    "reports.donations": "जमा",
    "reports.expenses": "खर्च",
    "reports.export": "निर्यात",
    "reports.import": "आयात",
    "reports.exportData": "डेटा निर्यात करा",
    "reports.importData": "डेटा आयात करा",
    "reports.exportTransactions": "व्यवहार निर्यात करा",
    "reports.exportSummary": "सारांश निर्यात करा",
    "reports.exportCategorySummary": "श्रेणी सारांश निर्यात करा",
    "reports.importTransactions": "व्यवहार आयात करा",
    "reports.selectDateRange": "दिनांक श्रेणी निवडा",
    "reports.fromDate": "पासून दिनांक",
    "reports.toDate": "पर्यंत दिनांक",
    "reports.selectTransactionType": "व्यवहार प्रकार निवडा",
    "reports.allTransactions": "सर्व व्यवहार",
    "reports.donationsOnly": "फक्त जमा",
    "reports.expensesOnly": "फक्त खर्च",
    "reports.rentIncomeOnly": "फक्त भाडे उत्पन्न",
    "reports.downloadCSV": "CSV डाउनलोड करा",
    "reports.downloadPDF": "PDF डाउनलोड करा",
    "reports.uploadCSV": "CSV फाइल अपलोड करा",
    "reports.selectFile": "फाइल निवडा",
    "reports.fileFormat": "फाइल स्वरूप",
    "reports.csvFormat":
      "CSV स्वरूप स्तंभांसह: दिनांक, प्रकार, श्रेणी, वर्णन, रक्कम",
    "reports.sampleFormat": "नमुना: 2024-01-15,जमा,सामान्य,मंदिर जमा,5000",
    "reports.fileSelected": "फाइल निवडली",
    "reports.noFileSelected": "कोणतीही फाइल निवडली नाही",
    "reports.importSuccess": "डेटा यशस्वीरित्या आयात केला",
    "reports.importError": "डेटा आयात करताना त्रुटी",
    "reports.invalidFormat": "अवैध फाइल स्वरूप",
    "reports.validationError": "डेटा प्रमाणीकरण अयशस्वी",
    "reports.processingImport": "आयात प्रक्रिया करत आहे...",
    "reports.exportSuccess": "डेटा यशस्वीरित्या निर्यात केला",
    "reports.exportError": "डेटा निर्यात करताना त्रुटी",
    "reports.generating": "अहवाल तयार करत आहे...",
    "reports.generatingPDF": "PDF तयार करत आहे...",
    "reports.pdfLanguage": "PDF भाषा",
    "reports.selectPDFLanguage": "PDF भाषा निवडा",
    "reports.englishPDF": "इंग्रजी PDF",
    "reports.marathiPDF": "मराठी PDF",
    "reports.financialReport": "आर्थिक अहवाल",
    "reports.generatedOn": "तयार केले",
    "reports.period": "कालावधी",
    "reports.srNo": "अ. क्र.",
    "reports.totalAmount": "एकूण रक्कम",
    "reports.transactionReport": "व्यवहार अहवाल",
    "reports.summaryReport": "सारांश अहवाल",
    "reports.categoryReport": "श्रेणी अहवाल",
    "reports.monthlyReport": "मासिक अहवाल",
    "reports.filters": "फिल्टर",
    "reports.clearFilters": "फिल्टर साफ करा",
    "reports.applyFilters": "फिल्टर लागू करा",
    "reports.filterByType": "प्रकारानुसार फिल्टर करा",
    "reports.filterByCategory": "श्रेणीनुसार फिल्टर करा",
    "reports.filterBySubCategory": "उप-श्रेणीनुसार फिल्टर करा",
    "reports.filterByMonth": "महिन्यानुसार फिल्टर करा",
    "reports.filterByDateRange": "दिनांक श्रेणीनुसार फिल्टर करा",
    "reports.selectCategory": "श्रेणी निवडा",
    "reports.selectSubCategory": "उप-श्रेणी निवडा",
    "reports.selectMonth": "महिना निवडा",
    "reports.selectYear": "वर्ष निवडा",
    "reports.noFiltersApplied": "कोणतेही फिल्टर लागू केलेले नाहीत",
    "reports.filteredResults": "फिल्टर केलेले परिणाम",
    "reports.showingResults": "{total} पैकी {count} व्यवहार दाखवत आहे",
    "reports.noTransactionsFound":
      "निवडलेल्या फिल्टरशी जुळणारे कोणतेही व्यवहार सापडले नाहीत",
    "reports.allTypes": "सर्व प्रकार",
    "reports.allCategories": "सर्व श्रेणी",
    "reports.allSubCategories": "सर्व उप-श्रेणी",
    "reports.allMonths": "सर्व महिने",
    "reports.viewMode": "दृश्य मोड",
    "reports.tableView": "तक्ता दृश्य",
    "reports.summaryView": "सारांश दृश्य",

    // Loan Management
    "loans.title": "कर्ज व्यवस्थापन",
    "loans.addLoan": "नवीन कर्ज जोडा",
    "loans.loanDetails": "कर्जाचे तपशील",
    "loans.loanAmount": "कर्जाची रक्कम",
    "loans.enterLoanAmount": "कर्जाची रक्कम प्रविष्ट करा",
    "loans.interestRate": "व्याजदर (%)",
    "loans.enterInterestRate": "मासिक व्याजदर प्रविष्ट करा",
    "loans.loanDuration": "कर्जाचा कालावधी (महिने)",
    "loans.enterLoanDuration": "कर्जाचा कालावधी महिन्यांत प्रविष्ट करा",
    "loans.disbursedDate": "वितरण दिनांक",
    "loans.monthlyEmi": "मासिक हप्ता",
    "loans.outstandingBalance": "थकीत शिल्लक",
    "loans.totalRepaid": "एकूण भरपाई",
    "loans.nextEmiDate": "पुढील हप्त्याची दिनांक",
    "loans.lastPaymentDate": "शेवटच्या भरपाईची दिनांक",
    "loans.loanStatus": "कर्जाची स्थिती",
    "loans.activeLoan": "सक्रिय",
    "loans.completedLoan": "पूर्ण",
    "loans.defaultedLoan": "बकाया",
    "loans.selectTenant": "भाडेकरू निवडा",
    "loans.selectAgreement": "करार निवडा",
    "loans.loanAmountRequired": "कर्जाची रक्कम आवश्यक आहे",
    "loans.loanAmountInvalid": "कृपया वैध कर्जाची रक्कम प्रविष्ट करा",
    "loans.interestRateRequired": "व्याजदर आवश्यक आहे",
    "loans.interestRateInvalid": "कृपया वैध व्याजदर प्रविष्ट करा",
    "loans.loanDurationRequired": "कर्जाचा कालावधी आवश्यक आहे",
    "loans.loanDurationInvalid": "कृपया वैध कालावधी प्रविष्ट करा",
    "loans.tenantRequired": "भाडेकरू निवड आवश्यक आहे",
    "loans.agreementRequired": "करार निवड आवश्यक आहे",
    "loans.disbursedDateRequired": "वितरण दिनांक आवश्यक आहे",
    "loans.successTitle": "कर्ज यशस्वीरित्या जोडले गेले!",
    "loans.successMessage": "कर्ज यशस्वीरित्या सिस्टममध्ये जोडले गेले आहे.",
    "loans.validationError":
      "कृपया सबमिट करण्यापूर्वी वैधता त्रुटी दुरुस्त करा.",
    "loans.emiPayment": "हप्ता भरणा",
    "loans.payEmi": "हप्ता भरा",
    "loans.calculateEmi": "हप्ता मोजा",
    "loans.loanAgreement": "कर्जाचा करार",
    "loans.uploadLoanAgreement": "कर्जाचा करार अपलोड करा",

    // Penalty Management
    "penalties.title": "दंड व्यवस्थापन",
    "penalties.addPenalty": "दंड जोडा",
    "penalties.penaltyDetails": "दंडाचे तपशील",
    "penalties.rentAmount": "भाडे रक्कम",
    "penalties.dueDate": "देय दिनांक",
    "penalties.paidDate": "भरपाई दिनांक",
    "penalties.penaltyRate": "दंड दर (%)",
    "penalties.penaltyAmount": "दंडाची रक्कम",
    "penalties.penaltyStatus": "दंडाची स्थिती",
    "penalties.pendingPenalty": "प्रलंबित",
    "penalties.paidPenalty": "भरलेले",
    "penalties.penaltyPaid": "दंड भरलेले",
    "penalties.penaltyPaidDate": "दंड भरपाईची दिनांक",
    "penalties.calculatePenalty": "दंड मोजा",
    "penalties.payPenalty": "दंड भरा",
    "penalties.lateFee": "विलंब शुल्क",
    "penalties.overdueRent": "थकीत भाडे",
    "penalties.automaticPenalty": "उशीरा भरपाईसाठी आपोआप दंड लावला",
    "penalties.penaltyCalculation":
      "दंड = भाडे रक्कम × दंड दर × विलंब दिवस / 30",

    // Shop Management
    "shop.title": "दुकान व्यवस्थापन",
    "shop.addShop": "नवीन दुकान जोडा",
    "shop.shopDetails": "दुकानाचे तपशील",
    "shop.shopNumber": "दुकान क्रमांक",
    "shop.enterShopNumber": "दुकान क्रमांक प्रविष्ट करा",
    "shop.shopSize": "दुकानाचा आकार (चौ फूट)",
    "shop.enterShopSize": "दुकानाचा आकार प्रविष्ट करा",
    "shop.monthlyRent": "मासिक भाडे",
    "shop.enterMonthlyRent": "मासिक भाडे प्रविष्ट करा",
    "shop.securityDeposit": "सुरक्षा ठेव",
    "shop.enterSecurityDeposit": "सुरक्षा ठेव प्रविष्ट करा",
    "shop.shopDescription": "वर्णन",
    "shop.enterShopDescription": "दुकानाचे वर्णन प्रविष्ट करा",
    "shop.shopStatus": "दुकानाची स्थिती",
    "shop.vacant": "रिकामे",
    "shop.occupied": "व्यापलेले",
    "shop.maintenance": "दुरुस्तीत",
    "shop.shopNumberRequired": "दुकान क्रमांक आवश्यक आहे",
    "shop.shopSizeRequired": "दुकानाचा आकार आवश्यक आहे",
    "shop.shopSizeInvalid": "कृपया वैध दुकानाचा आकार प्रविष्ट करा",
    "shop.monthlyRentRequired": "मासिक भाडे आवश्यक आहे",
    "shop.monthlyRentInvalid": "कृपया वैध मासिक भाडे प्रविष्ट करा",
    "shop.securityDepositRequired": "सुरक्षा ठेव आवश्यक आहे",
    "shop.securityDepositInvalid": "कृपया वैध सुरक्षा ठेव प्रविष्ट करा",
    "shop.successTitle": "दुकान यशस्वीरित्या जोडले गेले!",
    "shop.successMessage": "दुकान यशस्वीरित्या सिस्टममध्ये जोडले गेले आहे.",
    "shop.validationError":
      "कृपया सबमिट करण्यापूर्वी वैधता त्रुटी दुरुस्त करा.",
    "shop.shopAdded": "दुकान यशस्वीरित्या जोडले गेले",
    "shop.shopUpdated": "दुकान यशस्वीरित्या अपडेट केले गेले",
    "shop.shopDeleted": "दुकान यशस्वीरित्या हटविले गेले",
    "shop.cannotDeleteOccupiedShop": "व्यापलेले दुकान हटविता येत नाही",
    "shop.editShop": "दुकान संपादित करा",
    "shop.deleteShop": "दुकान हटवा",

    // Tenant Management
    "tenant.title": "भाडेकरू व्यवस्थापन",
    "tenant.addTenant": "नवीन भाडेकरू जोडा",
    "tenant.tenantDetails": "भाडेकरूचे तपशील",
    "tenant.tenantName": "भाडेकरूचे नाव",
    "tenant.enterTenantName": "भाडेकरूचे नाव प्रविष्ट करा",
    "tenant.tenantPhone": "फोन नंबर",
    "tenant.enterTenantPhone": "फोन नंबर प्रविष्ट करा",
    "tenant.tenantEmail": "ईमेल पत्ता",
    "tenant.enterTenantEmail": "ईमेल पत्ता प्रविष्ट करा",
    "tenant.tenantAddress": "पत्ता",
    "tenant.enterTenantAddress": "संपूर्ण पत्ता प्रविष्ट करा",
    "tenant.businessType": "व्यवसायाचा प्रकार",
    "tenant.enterBusinessType": "व्यवसायाचा प्रकार प्रविष्ट करा",
    "tenant.idProof": "ओळखपत्राचे तपशील",
    "tenant.enterIdProof": "ओळखपत्राचे तपशील प्रविष्ट करा (आधार/पॅन/इ.)",
    "tenant.tenantStatus": "भाडेकरूची स्थिती",
    "tenant.tenantNameRequired": "भाडेकरूचे नाव आवश्यक आहे",
    "tenant.tenantNameInvalid": "भाडेकरूचे नाव किमान 2 अक्षरांचे असावे",
    "tenant.tenantPhoneRequired": "फोन नंबर आवश्यक आहे",
    "tenant.tenantPhoneInvalid": "कृपया वैध 10-अंकी फोन नंबर प्रविष्ट करा",
    "tenant.tenantEmailInvalid": "कृपया वैध ईमेल पत्ता प्रविष्ट करा",
    "tenant.tenantAddressRequired": "पत्ता आवश्यक आहे",
    "tenant.businessTypeRequired": "व्यवसायाचा प्��कार आवश्यक आहे",
    "tenant.successTitle": "भाडेकरू यशस्वीरित्या जोडले गेले!",
    "tenant.successMessage": "भाडेकरू यशस्वीरित्या सिस्टममध्ये जोडले गेले आहे.",
    "tenant.validationError":
      "कृपया सबमिट करण्यापूर्वी वैधता त्रुटी दुरुस्त करा.",
    "tenant.tenantAdded": "भाडेकरू यशस्वीरित्या जोडले गेले",
    "tenant.tenantUpdated": "भाडेकरू यशस्वीरित्या अपडेट केले गेले",
    "tenant.tenantDeleted": "भाडेकरू यशस्वीरित्या हटविले गेले",
    "tenant.cannotDeleteTenantWithActiveAgreements":
      "सक्रिय कराराचे भाडेकरू हटविता येत नाहीत",
    "tenant.editTenant": "भाडेकरू संपादित करा",
    "tenant.deleteTenant": "भाडेकरू हटवा",

    // Agreement Management
    "agreement.title": "करार व्यवस्थापन",
    "agreement.createAgreement": "नवीन करार तयार करा",
    "agreement.agreementDetails": "कराराचे तपशील",
    "agreement.selectShop": "दुकान निवडा",
    "agreement.selectTenant": "भाडेकरू निवडा",
    "agreement.agreementDate": "कराराची दिनांक",
    "agreement.agreementDuration": "कालावधी (महिने)",
    "agreement.enterDuration": "कालावधी महिन्यांत प्रविष्ट करा",
    "agreement.agreementType": "कराराचा प्रकार",
    "agreement.residential": "निवासी",
    "agreement.commercial": "व्यावसायिक",
    "agreement.advanceRent": "आगाऊ भाडे",
    "agreement.enterAdvanceRent": "आगाऊ भाडे रक्कम प्रविष्ट करा",
    "agreement.totalDeposit": "एकूण ठेव",
    "agreement.shopRequired": "दुकान निवड आवश्यक आहे",
    "agreement.tenantRequired": "भाडेकरू निवड आवश्यक आहे",
    "agreement.agreementDateRequired": "कराराची दिनांक आवश्यक आहे",
    "agreement.durationRequired": "कालावधी आवश्यक आहे",
    "agreement.durationInvalid": "कृपया वैध कालावधी प्रविष्ट करा",
    "agreement.securityDepositRequired": "सुरक्षा ठेव आवश्यक आहे",
    "agreement.securityDepositInvalid": "कृपया वैध सुरक्षा ठेव प्रविष्ट करा",
    "agreement.advanceRentRequired": "आगाऊ भाडे आवश्यक आहे",
    "agreement.advanceRentInvalid": "कृपया वैध आगाऊ भाडे प्रविष्ट करा",
    "agreement.successTitle": "करार यशस्वीरित्या तयार केला गेला!",
    "agreement.successMessage": "भाडे करार यशस्वीरित्या तयार केला गेला आहे.",
    "agreement.validationError":
      "कृपया सबमिट करण्यापूर्वी वैधता त्रुटी दुरुस्त करा.",
    "agreement.agreementCreated": "करार यशस्वीरित्या तयार केला गेला",
    "agreement.agreementUpdated": "करार यशस्वीरित्या अपडेट केला गेला",
    "agreement.uploadAgreementDocument": "कराराचे दस्तऐवज अपलोड करा",
    "agreement.agreementDocument": "कराराचे दस्तऐवज",
    "agreement.activeAgreements": "सक्रिय करार",
    "agreement.viewAgreement": "करार पहा",
    "agreement.editAgreement": "करार संपादित करा",
    "agreement.terminateAgreement": "करार समाप्त करा",
    "agreement.renewAgreement": "करार नूतनीकरण करा",
    "agreement.expiredAgreements": "कालबाह्य झालेले करार",
    "agreement.terminatedAgreements": "समाप्त केलेले करार",

    // Enhanced Rent Management
    "rent.title": "भाडे व्यवस्थापन",
    "rent.shopManagement": "दुकान व्यवस्थापन",
    "rent.tenantManagement": "भाडेकरू व्यवस्थापन",
    "rent.agreements": "करार",
    "rent.rentCollection": "भाडे संकलन",
    "rent.addShop": "दुकान जोडा",
    "rent.addTenant": "भाडेकरू जोडा",
    "rent.createAgreement": "करार तयार करा",
    "rent.collectRent": "भाडे गोळा करा",
    "rent.shopNumber": "दुकान क्रमांक",
    "rent.shopSize": "दुकान आकार",
    "rent.monthlyRent": "मासिक भाडे",
    "rent.deposit": "ठेव",
    "rent.status": "स्थिती",
    "rent.vacant": "रिकामे",
    "rent.occupied": "व्यापलेले",
    "rent.maintenance": "देखभाल",
    "rent.tenantPhone": "भाडेकरू फोन",
    "rent.tenantEmail": "भाडेकरू ईमेल",
    "rent.tenantAddress": "भाडेकरू पत्ता",
    "rent.businessType": "व्यवसाय प्रकार",
    "rent.agreementDate": "करार दिनांक",
    "rent.agreementDuration": "करार कालावधी",
    "rent.rentDueDate": "भाडे देय दिनांक",
    "rent.lastPayment": "शेवटचे पेमेंट",
    "rent.nextDue": "पुढील देय",
    "rent.overdue": "थकीत",
    "rent.paid": "भरलेले",
    "rent.pending": "प्रलंबि���",
    "rent.agreementDetails": "करार तपशील",
    "rent.depositAmount": "ठेव रक्कम",
    "rent.securityDeposit": "सुरक्षा ठेव",
    "rent.advanceRent": "आगाऊ भाडे",
    "rent.totalDeposit": "एकूण ठेव",
    "rent.agreementType": "करार प्रकार",
    "rent.residential": "निवासी",
    "rent.commercial": "व्यावसायिक",
    "rent.paymentHistory": "पेमेंट इतिहास",
    "rent.enterShopNumber": "दुकान क्रमांक टाका",
    "rent.enterShopSize": "दुकान आकार टाका (चौ फूट)",
    "rent.enterMonthlyRent": "मासिक भाडे टाका",
    "rent.enterDeposit": "ठेव रक्कम टाका",
    "rent.enterTenantPhone": "भाडेकरू फोन टाका",
    "rent.enterTenantEmail": "भाडेकरू ईमेल टाका",
    "rent.enterTenantAddress": "भाडेकरू पत्ता टाका",
    "rent.enterBusinessType": "व्यवसाय प्रकार टाका",
    "rent.selectShop": "दुकान निवडा",
    "rent.selectTenant": "भाडेकरू निवडा",
    "rent.selectAgreementType": "करार प्रकार निवडा",
    "rent.agreementGenerated": "करार यशस्वीरित्या तयार केला",
    "rent.rentCollected": "भाडे यशस्वीरित्या गोळा केले",
    "rent.months": "महिने",
    "rent.years": "वर्षे",
    "rent.sqft": "चौ फूट",
    "rent.generateAgreement": "करार तयार करा",
    "rent.viewAgreement": "करार पहा",
    "rent.printAgreement": "करार मुद्रित करा",
    "rent.renewAgreement": "करार नूतनीकरण करा",
    "rent.terminateAgreement": "करार समाप्त करा",
    "rent.loanManagement": "कर्ज व्यवस्थापन",
    "rent.penaltyManagement": "दंड व्यवस्थापन",
    "rent.activeLoans": "सक्रिय कर्जे",
    "rent.pendingPenalties": "प्रलंबित दंड",
    "rent.collectRentWithLoan": "कर्ज/दंडासह भाडे गोळा करा",
    "rent.rentAndEmiCollection": "भाडे आणि हप्ता गोळा करणे",
    "rent.emiAmount": "हप्त्याची रक्कम",
    "rent.penaltyCollection": "दंड गोळा करणे",
    "rent.totalCollection": "एकूण गोळा",
    "rent.rentCollectionSuccess": "भाडे/हप्ता/दंड यशस्वीरित्या गोळा केले",
    "rent.noActiveLoans": "कोणतीही सक्रिय कर्जे सापडली नाहीत",
    "rent.noPendingPenalties": "कोणतेही प्रलंबित दंड सापडले नाहीत",

    // User Management
    "users.title": "वापरकर्ता व्यवस्थापन",
    "users.addUser": "वापरकर्ता जोडा",
    "users.addNewUser": "नवा वापरकर्ता जोडा",
    "users.editUser": "वापरकर्ता संपादित करा",
    "users.username": "वापरकर्ता नाव",
    "users.email": "ईमेल",
    "users.role": "भूमि��ा",
    "users.status": "स्थिती",
    "users.lastLogin": "शेवटचे लॉगिन",
    "users.actions": "कृती",
    "users.admin": "प्रशासक",
    "users.treasurer": "खजिनदार",
    "users.viewer": "दर्शक",
    "users.active": "सक्रिय",
    "users.inactive": "निष्क्रिय",
    "users.never": "कधीच नाही",
    "users.createAccount":
      "मंदिर ट्रस्ट व्यवस्थापन प्रणालीसाठी नवीन वापरकर्ता खाते तयार करा.",
    "users.updateInfo": "वापरकर्ता माहिती आणि परवानग्या अपडेट करा.",
    "users.updateUser": "वापरकर्ता अपडेट करा",
    "users.rolePermissions": "भूमिका परवानग्या:",
    "users.adminDesc":
      "वापरकर्ता व्यवस्थापनासह सर्व वैशिष्ट्यांमध्ये पूर्ण प्रवेश",
    "users.treasurerDesc": "जमा आणि खर्च व्��वस्थापित करू शकतात",
    "users.viewerDesc": "केवळ अहवाल आणि डॅशबोर्ड पाहू शकतात",

    // Common
    "common.actions": "कृती",
    "common.edit": "संपादित करा",
    "common.delete": "हटवा",
    "common.cancel": "रद्द करा",
    "common.save": "जतन करा",
    "common.close": "बंद करा",
    "common.submit": "सबमिट करा",
    "common.update": "अपडेट करा",
    "common.confirmDelete": "आपणास खात्री आहे की आपण हा आयटम हटवू इच्छिता? ही क्रिया पूर्ववत केली जाऊ शकत नाही.",
    "common.loading": "लोड होत आहे...",
    "common.search": "शोधा",
    "common.filter": "फिल्टर",
    "common.export": "निर्यात",
    "common.import": "आयात",
    "common.type": "प्रकार",
    "common.amount": "रक्कम",
    "common.date": "दिनांक",
    "common.description": "शेरा",
    "common.total": "एकूण",
    "common.currency": "₹",
    "common.noPermission":
      "आपल्याला या विभागात प्रवेश करण���याची परवानगी नाही. कृपया आपल्या प्रशासकाशी संपर्क साधा.",
    "common.view": "पहा",
    "common.print": "मुद्रित करा",
    "common.download": "डाउनलोड करा",
    "common.upload": "अपलोड करा",
    "common.select": "निवडा",
    "common.all": "सर्व",
    "common.none": "काहीही नाही",
    "common.add": "जोडा",
    "common.create": "तयार करा",
    "common.name": "नाव",
    "common.phone": "फोन",
    "common.email": "ईमेल",
    "common.address": "पत्ता",
    "common.success": "यश",
    "common.error": "त्रुटी",
    "common.warning": "चेतावणी",
    "common.info": "माहिती",
    "common.pickDate": "दिनांक निवडा",

    // Language
    "language.english": "English",
    "language.marathi": "मराठी",
    "language.switch": "भाषा बदला",

    // Document upload translations
    "documents.upload": "दस्तऐवज अपलोड करा",
    "documents.receiptImage": "पावती/बिल प्रतिमा",
    "documents.agreementDocument": "करार दस्तऐवज",
    "documents.supportingDocuments": "सहायक दस्तऐवज",
    "documents.uploadReceiptImage": "पावती/बिल प्रतिमा अपलोड करा",
    "documents.uploadAgreementDocument": "करार दस्तऐवज अपलोड करा",
    "documents.uploadSupportingDocuments": "सहायक दस्तऐवज अपलोड करा",
    "documents.dragAndDrop":
      "अपलोड करण्यासाठी क्लिक करा किंवा ड्रॅग आणि ड्रॉप करा",
    "documents.fileLimit": "कमाल 5 फाइल्स, प्रत्येक 300KB",
    "documents.supportedFormats": "JPG, PNG, PDF समर्थित",
    "documents.uploadSuccess": "दस्तऐवज यशस्वीरित्या अपलोड केले",
    "documents.uploadError": "दस्तऐवज अपलोड करण्यात अयशस्वी",
    "documents.fileSizeError": "फाइल आकार मर्यादा ओलांडली",
    "documents.fileTypeError": "फाइल ���्रकार समर्थित नाही",
    "documents.maxFilesError": "कमाल फाइल्स मर्यादा गाठली",
    "documents.viewDocument": "दस्तऐवज पहा",
    "documents.downloadDocument": "दस्तऐवज डाउनलोड क���ा",
    "documents.removeDocument": "दस्तऐवज काढा",
    "documents.noPreview": "पूर्वावलोकन उपलब्ध नाही",
    "documents.downloadToView": "पाहण्यासाठी डाउनलोड करा",
  },
};

interface LanguageProviderProps {
  children: ReactNode;
}

export function LanguageProvider({ children }: LanguageProviderProps) {
  const [language, setLanguageState] = useState<Language>("en");

  useEffect(() => {
    console.log('[LanguageProvider] Component mounting, checking for saved language...');
    const savedLanguage = localStorage.getItem("language") as Language;
    console.log('[LanguageProvider] Saved language from localStorage:', savedLanguage);
    
    if (savedLanguage && (savedLanguage === "en" || savedLanguage === "mr")) {
      console.log('[LanguageProvider] Setting language to saved value:', savedLanguage);
      setLanguageState(savedLanguage);
    } else {
      console.log('[LanguageProvider] No valid saved language, using default: en');
    }
  }, []);

  const setLanguage = (lang: Language) => {
    console.log('[LanguageProvider] Language change requested:', { from: language, to: lang });
    setLanguageState(lang);
    localStorage.setItem("language", lang);
    console.log('[LanguageProvider] Language saved to localStorage:', lang);
  };

  const t = (key: string): string => {
    const translation = translations[language][
      key as keyof (typeof translations)[typeof language]
    ] || key;
    
    // Only log missing translations to avoid spam
    // Skip warnings for system keys (common, auth) that are expected to exist
    if (translation === key && !key.startsWith('common.') && !key.startsWith('auth.')) {
      console.warn('[LanguageProvider] Missing translation for key:', key, 'in language:', language);
    }
    
    return translation;
  };

  console.log('[LanguageProvider] Rendering with language:', language);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    console.error('[useLanguage] Hook used outside of LanguageProvider');
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
